//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iMortacci
{
    public partial class configuration
    {
        #region Primitive Properties
    
        public virtual string key
        {
            get;
            set;
        }
    
        public virtual string value
        {
            get;
            set;
        }

        #endregion
    }
}
