//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iMortacci
{
    public partial class track
    {
        #region Primitive Properties
    
        public virtual int album_id
        {
            get;
            set;
        }
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string slug
        {
            get;
            set;
        }
    
        public virtual string title
        {
            get;
            set;
        }
    
        public virtual string description
        {
            get;
            set;
        }
    
        public virtual string alternate_desc
        {
            get;
            set;
        }
    
        public virtual System.DateTime created_at
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> release_at
        {
            get;
            set;
        }
    
        public virtual int playback_count
        {
            get;
            set;
        }
    
        public virtual string download_url
        {
            get;
            set;
        }
    
        public virtual string waveform_url
        {
            get;
            set;
        }
    
        public virtual int status
        {
            get;
            set;
        }

        #endregion
    }
}
